- name: start prometheus-server
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - prometheus.service

- name: restart prometheus-server
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - prometheus.service

- name: start alertmanager
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - alertmanager.service

- name: restart alertmanager
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - alertmanager.service
