- name: add prometheus group
  group:
    name: "{{ group }}"
    state: present

- name: add prometheus user
  user:
    name: "{{ user }}"
    group: "{{ group }}"

- name: create prometheus directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ prometheus.install_directory }}"
    - "{{ prometheus.rules_directory }}"

- name: install prometheus server
  unarchive:
    src: "{{ prometheus.source }}"
    dest: "{{ prometheus.install_directory }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: deploy prometheus config file
  template:
    src: templates/prometheus.yaml.j2
    dest: "{{ prometheus.config_file }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  notify:
    - start prometheus-server

- name: deploy prometheus service file
  template:
    src: templates/prometheus.service.j2
    dest: /etc/systemd/system/{{ prometheus.service }}.service
    owner: root
    group: root
    mode: 0644
  notify:
    - start prometheus-server

- name: deploy alerting rules
  template:
    src: templates/alerting_rules.j2
    dest: /opt/prometheus/rules/alerting.rules
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  notify:
    - restart prometheus-server
