- name: set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes

- name: install nginx reverse proxy
  package:
    name: nginx
    state: present
    update_cache: yes

- name: deploy nginx grafana configuration
  template:
    src: templates/nginx_grafana.conf.j2
    dest: /etc/nginx/conf.d/grafana.conf
    owner: root
    group: root
    mode: 0640
  notify:
    - restart nginx
